import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: {
    template: "%s | Flower shop",
    default: "Flower Shop"
  },
  description: "Generated by create next app",
};

type RootProps = {
  children: ReactNode
}

export default function RootLayout({ children }: RootProps) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
